services:
  gather3:
    build:
      context: .
      args:
        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: "6aee9d2f8c46f0c4984b16938fc91087"
        NEXT_PUBLIC_ARKIV_CHAIN: "kaolin"
    container_name: gather3
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3001"
    env_file:
      - .env.production
